### CSCN8000 - Artificial Intelligence Algorithms and Mathematics
#### Lab 1: Basic NumPy Operations

##### Part-A

##### Question 1

In [2]:
import numpy as np

# parameter 1 denotes teh starting element
# parameter 2 denotes the highest element ( might not be ncluded based on 3rd parameter)
# parameter 3 denotes the interval between numbers
array_1 = np.arange(1,20,3)
print(array_1)

[ 1  4  7 10 13 16 19]


##### Question 2

In [3]:
#Method 1 : Dont use this method. Always prefer Method 2
#initializing an array of length/shape 3 all initialized to zero
random_array_between_0_and_1 = np.zeros(3)
#for-loop calculating 3 random numbers and assigning to each index     
for i in range(3):
     random_number = np.random.random()
     random_array_between_0_and_1[i] = random_number

print(random_array_between_0_and_1)

#Method 2 : Better solution without loop and using numpy random with shape parameter
#This is a far better and easy solution when we consider complex shapes
shape=(3)
random_array_2_between_0_and_1 = np.random.random(shape)
print(random_array_2_between_0_and_1)

[0.59337721 0.19934635 0.12259702]
[0.8402797  0.9928345  0.97403521]


#### Question 3

In [4]:
sample_2d_array = np.array([[10,20,45],
                            [30,12,16],
                            [42,17,56]
                            ])

#To get first 2 rows we specify slicing 0:2 meaning including 0 until 2 ie. excluding 2
sample_2d_array_first_2_rows = sample_2d_array[0:2]
print('first two rows after slicing')
print(sample_2d_array_first_2_rows)
print('last two rowsafter slicing')
sample_2d_array_last_2_rows = sample_2d_array[1:3]
print(sample_2d_array_last_2_rows)




first two rows after slicing
[[10 20 45]
 [30 12 16]]
last two rowsafter slicing
[[30 12 16]
 [42 17 56]]


#### Question 4

In [5]:
shape = (2,2)
array_2d_first = np.random.randint(low=1, high=100, size=shape)
array_2d_second = np.random.randint(low=100, high=200, size=shape)
print(f'Array1\n {array_2d_first}')
print(f'Array1\n {array_2d_second}')

#using vstack and hstack we can stack elements
vertically_stacked_array = np.vstack((array_2d_first, array_2d_second))
print(f'Vertically stacked\n {vertically_stacked_array}')
horizontally_stacked_array = np.hstack((array_2d_first, array_2d_second))
print(f'Horizontally Stacked\n {horizontally_stacked_array}')

#using vsplit and hsplit we can split the array
vertically_split_vertically_stacked_array = np.vsplit(vertically_stacked_array, 4)
print(f'Collection of arrays after Vertical split of Vertically stacked array\n {vertically_split_vertically_stacked_array}')

horizontally_split_vertically_stacked_array = np.hsplit(vertically_stacked_array, 2)
print(f'Collection of arrays after Horizontal split of Vertically stacked array\n {horizontally_split_vertically_stacked_array}')

Array1
 [[91 17]
 [59 85]]
Array1
 [[149 170]
 [187 192]]
Vertically stacked
 [[ 91  17]
 [ 59  85]
 [149 170]
 [187 192]]
Horizontally Stacked
 [[ 91  17 149 170]
 [ 59  85 187 192]]
Collection of arrays after Vertical split of Vertically stacked array
 [array([[91, 17]]), array([[59, 85]]), array([[149, 170]]), array([[187, 192]])]
Collection of arrays after Horizontal split of Vertically stacked array
 [array([[ 91],
       [ 59],
       [149],
       [187]]), array([[ 17],
       [ 85],
       [170],
       [192]])]


> Note that we had to use 2 as parameter when splitting vertically stacked array horizontally. This is because each array in the vertical stack contained only 2 elements. Had the horizontal split been performed on a horizontally stacked 2x2 array then we could have used 4 also since in a single row we would have 8 items.

#### Question 5

In [6]:
x_matrix = np.array([[5,7,2],
                   [4,5,6],
                   [7,4,2]])
y_matrix = np.array([[4,2],
                    [6,2],
                    [4,2]]) 

#defining a function for calculating and printing the dot product in case its possible otherwise prints not possible
def matrix_multiplication(np1, np2):
    _, column_count_1 = np1.shape
    row_count_2, _ = np2.shape
    print(f'first matrix \n {np1}')
    print(f'second matrix \n {np2}')
    try:
        result = np.matmul(np1,np2)
        print(f"Multiplication is possible because \ncolumn count of 1st matrix : {column_count_1} matches with row count of 2nd matrix : {row_count_2} and the result is \n{result}")
    except ValueError:
        print(f"Multiplication is not possible")
        print(f'Reason : Column count of 1st matrix : {column_count_1} doesnt match with row count of 2nd matrix : {row_count_2}')
    return

#part 1 : checking if its possible to multiply these matrices
print('********* Is it possible to multiply these matrices ? ****************')
matrix_multiplication(x_matrix, y_matrix)

#part2 : Quickest way to demonstarte will be changing the order of the matrix multilication
print('********* Demonstrate the case when it is not possible to. ****************')
matrix_multiplication(y_matrix,x_matrix)

********* Is it possible to multiply these matrices ? ****************
first matrix 
 [[5 7 2]
 [4 5 6]
 [7 4 2]]
second matrix 
 [[4 2]
 [6 2]
 [4 2]]
Multiplication is possible because 
column count of 1st matrix : 3 matches with row count of 2nd matrix : 3 and the result is 
[[70 28]
 [70 30]
 [60 26]]
********* Demonstrate the case when it is not possible to. ****************
first matrix 
 [[4 2]
 [6 2]
 [4 2]]
second matrix 
 [[5 7 2]
 [4 5 6]
 [7 4 2]]
Multiplication is not possible
Reason : Column count of 1st matrix : 2 doesnt match with row count of 2nd matrix : 3


#### Question 6

In [7]:
x_array = np.array([2, -1, -8])
y_array = np.array([3, 1, -2])

def shape_and_dimension(array):
    print(f'shape of vector : {array.shape}')
    print(f'dimensions of vector : {array.ndim}')

print("*********** Find the Shape, Number of dimensions of vector x. ****************")
shape_and_dimension(x_array)

#Reshaping to (3,1)
print("************** Reshape the vector ***************")
reshaped_vector_x = x_array.reshape(3,1)
reshaped_vector_y = y_array.reshape(3,1)
print(f'Reshaped X \n {reshaped_vector_x}')
shape_and_dimension(reshaped_vector_x)

print(f'Reshaped Y \n {reshaped_vector_y}')
shape_and_dimension(reshaped_vector_y)


*********** Find the Shape, Number of dimensions of vector x. ****************
shape of vector : (3,)
dimensions of vector : 1
************** Reshape the vector ***************
Reshaped X 
 [[ 2]
 [-1]
 [-8]]
shape of vector : (3, 1)
dimensions of vector : 2
Reshaped Y 
 [[ 3]
 [ 1]
 [-2]]
shape of vector : (3, 1)
dimensions of vector : 2


#### Question 7

#### How does broadcasting work?
Broadcasting is a powerful feature in numpy library for doing operations on arrays with different shapes.
The concept of broadcasting relies **on 'stretching' one of the two arrays** so that mathematical operations can be
applied to the two arrays involved. **Broadcasting is memory efficient and fast**. It is memory efficient because 
it **doesn't actually create a copy of the array to be stretched nor does it replicate the data internally for stretching**. 
Broadcasting won't work for all pairs of shapes of arrays. It has a set of rules which is summarized in my own words below.
> When comparing the rightmost non matching dimensions of two arrays one of them needs to be 1 and the remaining dimensions to the left of that array also needs to be 1.

Another important thing to notice here
> Broadcasting is inherently applied by numpy when we use mathematical operators on two numpy arrays. We don't need to use special characters, operators or functions.

#### Demonstration of broadcasting

In [8]:
# In order to showcase broadcasting feature we are writing a function for applying multiplication and division using broadcasting
def broadcasting_demo(array1, array2, title):
    print(f'{title}')
    print(f'Array 1 : Shape : {array1.shape} \n{array1}')
    print(f'Array 2 : Shape : {array2.shape} \n{array2}')
    try:
        product = array1 * array2
        division = array1 / array2
        print(f'Result after multiplication \n{product}')
        print(f'Result after division \n {division}')
    except ValueError:
        print(f'Broadcasting is not possible because array1 shape : {array1.shape} and array2 shape : {array2.shape} is not compatible for broadcasting')

##### Example 1

In [9]:

#Example 1 : Same shape for both arrays
array_1 = np.array([[10,20,30],
                   [40,50,60],
                   [70,80,90]])
array_2 = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])

broadcasting_demo(array_1, array_2, 'Example 1')




Example 1
Array 1 : Shape : (3, 3) 
[[10 20 30]
 [40 50 60]
 [70 80 90]]
Array 2 : Shape : (3, 3) 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Result after multiplication 
[[ 10  40  90]
 [160 250 360]
 [490 640 810]]
Result after division 
 [[10. 10. 10.]
 [10. 10. 10.]
 [10. 10. 10.]]


> Broadcasting is possible for identically shaped arrays

##### Example 2 : different shapes

In [10]:
sample_2_array_1 = np.array([[10,20,30],
                   [40,50,60],
                   [70,80,90]])
sample_2_array_2 = np.array([[1,2,3]])

broadcasting_demo(sample_2_array_1, sample_2_array_2, 'Example 2')


Example 2
Array 1 : Shape : (3, 3) 
[[10 20 30]
 [40 50 60]
 [70 80 90]]
Array 2 : Shape : (1, 3) 
[[1 2 3]]
Result after multiplication 
[[ 10  40  90]
 [ 40 100 180]
 [ 70 160 270]]
Result after division 
 [[10. 10. 10.]
 [40. 25. 20.]
 [70. 40. 30.]]


> Here we can see that even though the shape of the two arrays were different the operation was possible. Basically array2 was stretched resulting in the same shape ie [[1,2,3], [1,2,3], [1,2,3]]

##### Example 3 : what if we try the opposite of the previous example ?

In [11]:
# Note the parameters have been swapped
broadcasting_demo(sample_2_array_2, sample_2_array_1, 'Example 3')

Example 3
Array 1 : Shape : (1, 3) 
[[1 2 3]]
Array 2 : Shape : (3, 3) 
[[10 20 30]
 [40 50 60]
 [70 80 90]]
Result after multiplication 
[[ 10  40  90]
 [ 40 100 180]
 [ 70 160 270]]
Result after division 
 [[0.1        0.1        0.1       ]
 [0.025      0.04       0.05      ]
 [0.01428571 0.025      0.03333333]]


> Order is not important for multiplication and division and applying broadcasting

Example 4: More than 2 dimensions

In [12]:
sample_4_array_1 = np.array([[[10,20,30],
                   [40,50,60],
                   [70,80,90]],
                   [[1,2,3],
                   [4,5,6],
                   [7,8,9]]])
sample_4_array_2 = np.array([[1,2,3]])
broadcasting_demo(sample_4_array_1, sample_4_array_2, 'Example 4')

Example 4
Array 1 : Shape : (2, 3, 3) 
[[[10 20 30]
  [40 50 60]
  [70 80 90]]

 [[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]]
Array 2 : Shape : (1, 3) 
[[1 2 3]]
Result after multiplication 
[[[ 10  40  90]
  [ 40 100 180]
  [ 70 160 270]]

 [[  1   4   9]
  [  4  10  18]
  [  7  16  27]]]
Result after division 
 [[[10.  10.  10. ]
  [40.  25.  20. ]
  [70.  40.  30. ]]

 [[ 1.   1.   1. ]
  [ 4.   2.5  2. ]
  [ 7.   4.   3. ]]]


##### Example 5

In [13]:
sample_5_array_1 = np.array([[[10,20,30],
                   [40,50,60],
                   [70,80,90]],
                   [[1,2,3],
                   [4,5,6],
                   [7,8,9]]])
sample_5_array_2 = np.array([[1,2,3], [4,5,6]])
broadcasting_demo(sample_5_array_1, sample_5_array_2, 'Example 5')


Example 5
Array 1 : Shape : (2, 3, 3) 
[[[10 20 30]
  [40 50 60]
  [70 80 90]]

 [[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]]
Array 2 : Shape : (2, 3) 
[[1 2 3]
 [4 5 6]]
Broadcasting is not possible because array1 shape : (2, 3, 3) and array2 shape : (2, 3) is not compatible for broadcasting


> Compatibility fails since the 2nd dimension for first array and second array are not same ie 3 and 2 and none of them is equal to 1 which restricts numpy from properly stretching and matching one array to the other.

##### Final Example : what modification in last example will make it compatible ?

In [14]:
sample_6_array_1 = np.array([[[10,20,30],
                   [40,50,60]],
                   [[1,2,3],
                   [4,5,6]]])
sample_6_array_2 = np.array([[1,2,3], [4,5,6]])
broadcasting_demo(sample_6_array_1, sample_6_array_2, 'Example 6')

Example 6
Array 1 : Shape : (2, 2, 3) 
[[[10 20 30]
  [40 50 60]]

 [[ 1  2  3]
  [ 4  5  6]]]
Array 2 : Shape : (2, 3) 
[[1 2 3]
 [4 5 6]]
Result after multiplication 
[[[ 10  40  90]
  [160 250 360]]

 [[  1   4   9]
  [ 16  25  36]]]
Result after division 
 [[[10. 10. 10.]
  [10. 10. 10.]]

 [[ 1.  1.  1.]
  [ 1.  1.  1.]]]


> Here we removed one row from each matrix from the first array which made the array 1 shape 2,2,3 which now becomes compatible with array2 shape which is 2,3

## Part B - Linear Equations

#### Question B.1

- 4x + y - 2z = 10
- 2x - 3y + 2z = -4
- x + 2y + 3z = 6

#### Finding singularity
In order to find if a system is singular we can find the determinant and see if its zero. If so it means that the system is singular and doesnt have a unique solution.

In [18]:
# Representing the above linear equations as Ax = b
coefficient_matrix_1 = np.array([[4,1,-2],
                               [2,-3,2],
                               [1,2,3]])
result_vector_1 = np.array([10,-4,6])

def check_determinant(nparray):
    determinant = np.linalg.det(nparray)
    if determinant != 0:
        print(f'Determinant is {determinant} which is non-zero, hence the system of linear equation is solvable')
    else:
        print(f'Determinant is {determinant} hence the system is singular and there is no unique solution or zero solutions')

check_determinant(coefficient_matrix_1)

solution_vector = np.linalg.solve(coefficient_matrix_1, result_vector_1)

# just trying to use splits and stacks we used to solve PART A
column_names = np.array(['x','y','z'])
combined_result = np.vstack((column_names, solution_vector))
result = np.hsplit(combined_result,3)

print(f'The solution for the linear equation is \n{solution_vector} \n\n {result}')

coefficient_matrix_2 = np.array([[4,-3,1], [2,1,3], [-1,2,-5]])
result_vector_2 = np.array([-10, 0, 17])
solution_vector_2 = np.linalg.solve(coefficient_matrix_2, result_vector_2)
print(f'The solution for the linear equation is \n{solution_vector_2}')



Determinant is -70.00000000000003 which is non-zero, hence the system of linear equation is solvable
The solution for the linear equation is 
[ 1.8  2.4 -0.2] 

 [array([['x'],
       ['1.7999999999999998']], dtype='<U32'), array([['y'],
       ['2.4']], dtype='<U32'), array([['z'],
       ['-0.2']], dtype='<U32')]
The solution for the linear equation is 
[ 1.  4. -2.]


#### Question B.2

- 2x - y + 3z + 4w = 10
- 4x - 2y + 6z + 8w = 20
- 3x + y - 2z + 2w = 3
- x + 3y - 4z + w = -1

In [16]:
coefficient_matrix_2 = np.array([[2,-1,3,4],
                              [4,-2,6,8],
                              [3,1,-2,2],
                              [1,3,-4,1]])
result_vector_2 = np.array([10,20,3,-1])

check_determinant(coefficient_matrix_2)

Determinant is 0.0 hence the system is singular and there is no unique solution or zero solutions


> We checked the determinant after creating the coefficient matrix and the determinant was found to be zero. This indicates that the system is singular and has more than 1 unique solutions or no solutions at all.

##### Method 2 for checking singularity using Ranks

In [17]:
def rank_of_array_for_2d_arrays(nparray):
    if nparray.ndim > 2:
        print('Since dimension is greater than 2 rank cannot be computed easily without using tensors.')
        return
    rank = np.linalg.matrix_rank(nparray)
    row_count, column_count = nparray.shape
    if rank < min(row_count, column_count):
        print(f'Rank {rank} is less than row/column {row_count}/{column_count} count hence system is singular and the system is not solvable')
    else:
        print(f'The system is solvable. Verified using rank {rank} row/column {row_count}/{column_count} and rank is same as the max value of row / column')
    return

print('Checking if Part B.2 linear equations are solvable using rank')
rank_of_array_for_2d_arrays(coefficient_matrix_2)

print('\n\n Checking if Part B.1 linear equations are solvable using rank')
rank_of_array_for_2d_arrays(coefficient_matrix_1)


Checking if Part B.2 linear equations are solvable using rank
Rank 3 is less than row/column 4/4 count hence system is singular and the system is not solvable


 Checking if Part B.1 linear equations are solvable using rank
The system is solvable. Verified using rank 3 row/column 3/3 and rank is same as the max value of row / column
